name: Daily Commit
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "22f1001679@ds.study.iitm.ac.in"
      - name: Create a new commit
        run: |
          echo "$(date)" > update.txt
          git add update.txt
          git commit -m "Automated commit $(date)"
          git push